In [58]:
#imports
import pandas as pd

In [59]:
#read the cleaned dataset with a pandas dataframe
df = pd.read_csv('newdata.csv', parse_dates=['Date'])

In [60]:
#sort the data by the values of the date and location column
df.sort_values(by=['Date','Location'], inplace=True)

In [61]:
#have a first look on te data
df.head()

,Unnamed: 0,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,...,Second_Booster,Second_Booster_50Plus,Second_Booster_50Plus_Vax_Pct,Second_Booster_65Plus,Second_Booster_65Plus_Vax_Pct,Second_Booster_Janssen,Second_Booster_Moderna,Second_Booster_Pfizer,Second_Booster_Unk_Manuf,Date2
27107,34973,2020-12-14,51,AK,4875,0,0,0,0,666,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020
27131,35005,2020-12-14,51,AL,6825,0,0,0,0,139,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020
27130,35004,2020-12-14,51,AR,3900,0,0,0,0,129,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020
27124,34997,2020-12-14,51,AZ,21450,0,0,0,0,295,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020
27136,35010,2020-12-14,51,CA,33150,0,0,0,0,84,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020

In [62]:
#read the geospatial data that was brought from kaggle which is a dataset with the longitudes and latitudes of the 50 states.
dfgeov = pd.read_csv('statelatlong.csv')

In [63]:
#sorting the geospatial data by the state column
dfgeov.sort_values(['State'], inplace= True)

In [64]:
#have a first look on the geospatial data
dfgeov.head()

  State   Latitude   Longitude        City
1    AK  61.302501 -158.775020      Alaska
0    AL  32.601011  -86.680736     Alabama
3    AR  34.751928  -92.131378    Arkansas
2    AZ  34.168219 -111.930907     Arizona
4    CA  37.271875 -119.270415  California

In [65]:
#merge the geospatial data with the cleaned dataset by the values of both location and state values.
dfinal = df.merge(dfgeov, how='inner', left_on='Location', right_on='State')

In [66]:
#having a look on the new data to check if the merge went right.
dfinal.head()

,Unnamed: 0,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,...,Second_Booster_65Plus_Vax_Pct,Second_Booster_Janssen,Second_Booster_Moderna,Second_Booster_Pfizer,Second_Booster_Unk_Manuf,Date2,State,Latitude,Longitude,City
0,34973,2020-12-14,51,AK,4875,0,0,0,0,666,...,0.0,0.0,0.0,0.0,0.0,2020,AK,61.302501,-158.77502,Alaska
1,34953,2020-12-15,51,AK,12675,0,0,0,0,1733,...,0.0,0.0,0.0,0.0,0.0,2020,AK,61.302501,-158.77502,Alaska
2,34867,2020-12-16,51,AK,26325,0,0,0,0,3599,...,0.0,0.0,0.0,0.0,0.0,2020,AK,61.302501,-158.77502,Alaska
3,34818,2020-12-17,51,AK,26325,0,0,0,0,3599,...,0.0,0.0,0.0,0.0,0.0,2020,AK,61.302501,-158.77502,Alaska
4,34761,2020-12-18,51,AK,26325,0,0,0,0,3599,...,0.0,0.0,0.0,0.0,0.0,2020,AK,61.302501,-158.77502,Alaska

In [67]:
#sort the data by the values of the data and location column
dfinal.sort_values(by=['Date','Location'], inplace=True)

In [68]:
#drop the (Unnamed: 0) column.
dfinal.drop('Unnamed: 0', axis=1, inplace=True)

In [69]:
#drop the (State) column because its values are duplicated.
dfinal.drop('State', axis=1, inplace=True)

In [70]:
#have a final look on the data
dfinal.head()

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_5Plus,...,Second_Booster_65Plus,Second_Booster_65Plus_Vax_Pct,Second_Booster_Janssen,Second_Booster_Moderna,Second_Booster_Pfizer,Second_Booster_Unk_Manuf,Date2,Latitude,Longitude,City
0,2020-12-14,51,AK,4875,0,0,0,0,666,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2020,61.302501,-158.775020,Alaska
543,2020-12-14,51,AL,6825,0,0,0,0,139,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2020,32.601011,-86.680736,Alabama
1086,2020-12-14,51,AR,3900,0,0,0,0,129,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2020,34.751928,-92.131378,Arkansas
1629,2020-12-14,51,AZ,21450,0,0,0,0,295,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2020,34.168219,-111.930907,Arizona
2172,2020-12-14,51,CA,33150,0,0,0,0,84,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2020,37.271875,-119.270415,California

In [71]:
#checking if there are any messing values
dfinal.isnull().sum()

Date                        0
MMWR_week                   0
Location                    0
Distributed                 0
Distributed_Janssen         0
                           ..
Second_Booster_Unk_Manuf    0
Date2                       0
Latitude                    0
Longitude                   0
City                        0
Length: 95, dtype: int64

In [72]:
#check the data type of the new data
dfinal.dtypes

Date                        datetime64[ns]
MMWR_week                            int64
Location                            object
Distributed                          int64
Distributed_Janssen                  int64
                                 ...
Second_Booster_Unk_Manuf           float64
Date2                                int64
Latitude                           float64
Longitude                          float64
City                                object
Length: 95, dtype: object

In [73]:
#upload the new data into csv file.
dfinal.to_csv('geodata.csv')